### ISSUE TITLE
It seems like the generated protobuf Java files are missing from the repo. 

### ISSUE THREAD

**Issue by ajselvig** [dkhenry/rethinkjava#1]
Doesn't it make sense to add them since they'll rarely change and then you won't force users to install an additional toolchain?

**Comment by dkhenry** [comment]
Normally I would oppose checking in generated source to version control, however since it can be useful to directly manipulate the protobuf for some of the queries I think it warrents an exception. I will add it in the next push

**Comment by ajselvig** [comment]
Cool, thanks. I would generally agree with you about not checking in generated source, but I think this is a good exception.

**Comment by dkhenry** [comment]
I haven't added the generated proto file, but I think I have found a good compromise. Essentially here is my thinking. If your pulling down this repo its going to be because you want to work on it or integrate it into something your doing. Either way your not a consumer. If your just a consumer you will use the compiled binary which has the protoc file compiled in. Prehaps however you want to see the code so you can use the unexposed bits. In that case I now added a src jar and a javadoc jar. Those should give you all the documentation you need about the compiled source.

**Comment by ajselvig** [comment]
Okay, fair enough. Thanks.
